// src/lib/FetchData.svelte
<script lang="ts">
	import axios from 'axios';
	import Papa from 'papaparse';
	import fileSaver from 'file-saver';
	const { saveAs } = fileSaver;

	const year = new Date().getFullYear();

	function delay(ms: number) {
		return new Promise((resolve) => setTimeout(resolve, ms));
	}

	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	async function scryfallGet(url: string, retries = 3): Promise<any> {
		try {
			return await axios.get(url);
		} catch (err: unknown) {
			const axiosErr = err as {
				response?: { status: number; data?: { details?: string } };
				message: string;
			};
			if (axiosErr.response?.status === 429 && retries > 0) {
				const details = axiosErr.response.data?.details ?? '';
				const match = details.match(/try again after (\d+) seconds/);
				const waitMs = match ? parseInt(match[1]) * 1000 : 60000;
				await delay(waitMs);
				return scryfallGet(url, retries - 1);
			}
			throw err;
		}
	}

	function getLanguageName(code: string | number): string {
		const languages: Record<string | number, string> = {
			1: 'English',
			2: 'French',
			3: 'German',
			4: 'Spanish',
			5: 'Italian',
			6: 'Simplified Chinese',
			7: 'Japanese',
			8: 'Portuguese',
			9: 'Russian',
			10: 'Korean',
			11: 'Traditional Chinese'
		};
		return languages[code] || '';
	}

	function getConditionName(code: string): string {
		const conditions: Record<string, string> = {
			MT: 'M',
			NM: 'NM',
			EX: 'LP',
			GD: 'MP',
			LP: 'MP',
			PL: 'HP',
			PO: 'D'
		};
		return conditions[code] || 'NM';
	}

	function getFoil(isFoil: string, finishes: string[]): string {
		if (isFoil === '1') {
			if (finishes.includes('etched') && !finishes.includes('foil')) {
				return 'etched';
			} else {
				return 'foil';
			}
		} else {
			return '';
		}
	}

	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	let data = $state<any[]>([]);
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	let missingIds = $state<any[]>([]);
	let loading = $state(false);
	let error = $state<string | string[] | null>(null);
	let file = $state<File | null>(null);
	let fileContent = $state('');
	let fileChanged = $state(true);
	let copied = $state<boolean | null>(null);

	const disableLoadButton = $derived(loading || !fileChanged);
	const sortedMissingIds = $derived(
		[...missingIds].sort((a, b) => a.reason.localeCompare(b.reason))
	);

	function handleFileUpload(event: Event) {
		const target = event.target as HTMLInputElement;
		const selectedFile = target.files?.[0];
		if (!selectedFile) return;

		file = selectedFile;
		fileChanged = true;
		error = null;

		const reader = new FileReader();
		reader.onload = function (e) {
			fileContent = (e.target as FileReader).result as string;
		};
		reader.onerror = function () {
			error = reader.error?.message ?? 'Unknown error reading file.';
		};
		reader.readAsText(selectedFile);
	}

	async function handleLoadFile() {
		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		const updates: Record<number, any> = {};

		if (!file) {
			error = 'No file selected.';
			missingIds = [];
			data = [];
			copied = false;
			fileChanged = false;
			return;
		}

		loading = true;
		error = null;
		missingIds = [];
		data = [];
		copied = false;

		Papa.parse(fileContent, {
			header: true,
			// eslint-disable-next-line @typescript-eslint/no-explicit-any
			complete: async (results: any) => {
				const fields = results.meta.fields as string[];
				if (
					!(
						fields.includes('idProduct') ||
						(fields.includes('Product ID') &&
							fields.includes('Article') &&
							fields.includes('Expansion'))
					)
				) {
					error = [
						'Invalid file format.',
						'The file must include either an "idProduct" column header or all three of the following column headers: "Product ID", "Article", and "Expansion".',
						'Are you sure this is a CardMarket CSV file?'
					];
					loading = false;
					fileChanged = false;
					missingIds = [];
					data = [];
					copied = false;
					return;
				}

				for (let index = 0; index < results.data.length; index++) {
					// eslint-disable-next-line @typescript-eslint/no-explicit-any
					const row: any = results.data[index];
					if (index > 0) await delay(1000);

					let isToken = '';
					let expansion = row.Expansion || '';
					let article = row.Article || '';

					expansion = expansion.replace(': Extras', '');
					if (['Mystery Booster', 'The List'].includes(expansion)) {
						expansion = 'PLST';
					} else if (expansion === '30th Anniversary Celebration') {
						expansion = 'P30A';
					}
					if (expansion.includes('Commander:')) {
						expansion = expansion.replace('Commander: ', '');
					}
					expansion = expansion.replace(': Promos', ' Promos');
					article = article.replace(/\(.*\)/, '');
					if (article.includes('Token')) {
						article = article.replace(/Token.*$/, '');
						expansion += ' Tokens';
						isToken = '+t:token';
					}

					const idProduct = row['Product ID'] || row.idProduct;
					const count = row.groupCount || row.Amount;
					const purchasePrice = row.price || row['Article Value'];

					if (row.Category && row.Category !== 'Magic Single') {
						missingIds = [
							...missingIds,
							{
								id: idProduct,
								line: index + 2,
								reason: 'This is not a Magic card.'
							}
						];
						continue;
					}

					try {
						const response = await scryfallGet(
							`https://api.scryfall.com/cards/cardmarket/${idProduct}`
						);
						if (response.status === 200) {
							const card = response.data;
							updates[index] = {
								Count: count,
								Name: card.name,
								Edition: card.set,
								Language: getLanguageName(row.idLanguage) || '',
								Foil: getFoil(row.isFoil, card.finishes),
								CollectorNumber: card.collector_number,
								Alter: row.isAltered === 'true' ? 'TRUE' : 'FALSE',
								Condition: getConditionName(row.condition) || 'NM',
								PurchasePrice: purchasePrice
							};
						}
					} catch (err: unknown) {
						const axiosErr = err as { response?: { status: number }; message: string };
						if (
							axiosErr.response &&
							axiosErr.response.status === 404 &&
							row.Article &&
							row.Expansion
						) {
							try {
								const response = await scryfallGet(
									`https://api.scryfall.com/cards/search?q=e%3A%22${expansion}%22+${article}${isToken}`
								);
								if (response.status === 200) {
									const card = response.data;
									updates[index] = {
										Count: count,
										Name: card.data[0].name,
										Edition: card.data[0].set,
										Language: getLanguageName(row.idLanguage) || '',
										Foil: getFoil(row.isFoil, card.data[0].finishes),
										CollectorNumber: card.data[0].collector_number,
										Alter: row.isAltered === 'true' ? 'TRUE' : 'FALSE',
										Condition: getConditionName(row.condition) || 'NM',
										PurchasePrice: purchasePrice
									};
									missingIds = [
										...missingIds,
										{
											id: idProduct,
											line: index + 2,
											name: card.data[0].name,
											uri: card.data[0].scryfall_uri,
											reason: 'The printing added to your Moxfield CSV may be incorrect.'
										}
									];
								}
							} catch (innerErr: unknown) {
								const innerAxiosErr = innerErr as {
									response?: { status: number };
									message: string;
								};
								if (
									innerAxiosErr.response &&
									innerAxiosErr.response.status == 404 &&
									row.Category == 'Magic Single'
								) {
									missingIds = [
										...missingIds,
										{
											id: idProduct,
											line: index + 2,
											name: article,
											expansion: expansion,
											reason: 'Unable to find this card on Scryfall.'
										}
									];
								}
							}
						} else if (axiosErr.response && axiosErr.response.status === 404 && !row.Category) {
							missingIds = [
								...missingIds,
								{
									id: idProduct,
									line: index + 2,
									reason: 'Scryfall is missing this CardMarket ID.'
								}
							];
						} else {
							if (axiosErr.response && axiosErr.response.status !== 404) {
								error = axiosErr.message;
							}
							fileChanged = false;
							data = [];
							copied = false;
						}
					}
				}

				data = Object.keys(updates)
					.sort((a, b) => Number(a) - Number(b))
					.map((key) => updates[Number(key)]);
				loading = false;
				fileChanged = false;
			},
			error: async (err: { message: string }) => {
				error = err.message;
				loading = false;
				missingIds = [];
				data = [];
				copied = false;
			}
		});
	}

	function downloadData() {
		const csv = Papa.unparse(data);
		const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
		saveAs(blob, 'output.csv');
	}
</script>

<div
	class="flex min-h-screen flex-col items-center justify-center bg-tropical_indigo px-4 text-linen"
>
	<h1 class="mt-5 mb-2 text-center text-5xl font-bold lg:mb-24">
		CardMarket to Moxfield CSV Converter
	</h1>

	<input
		type="file"
		accept=".csv"
		onchange={handleFileUpload}
		class="my-4 w-full max-w-md rounded-md border border-linen bg-french_gray p-2 text-dark_purple shadow-md"
	/>

	<button
		onclick={handleLoadFile}
		class="my-4 w-full max-w-xs rounded-md border border-linen p-2 shadow-md {error
			? 'bg-slate_blue text-linen'
			: 'bg-french_gray text-dark_purple'}"
		disabled={disableLoadButton}
	>
		{#if error}
			Error
		{:else if loading}
			Loading
		{:else if fileChanged}
			Load CSV File
		{:else}
			Data Loaded
		{/if}
	</button>

	<div
		class="my-4 flex w-full max-w-3xl flex-col space-y-4 xl:max-w-6xl xl:flex-row xl:space-y-0 xl:space-x-4 {data.length >
		0
			? ''
			: 'xl:flex-col'}"
	>
		<textarea
			value={fileContent ||
				'Please load your CardMarket CSV file. The input data will show here once loaded.'}
			readonly
			class="h-50 resize-none rounded-md border border-linen bg-dark_purple p-2 shadow-md lg:h-125 {data.length >
			0
				? 'xl:w-1/2'
				: 'xl:w-full'}"
		></textarea>
		{#if data.length > 0}
			<textarea
				value={Papa.unparse(data)}
				readonly
				class="h-50 resize-none rounded-md border border-linen bg-dark_purple p-2 shadow-md lg:h-125 xl:w-1/2"
			></textarea>
		{/if}
	</div>

	{#if loading}
		<div class="my-4 w-full max-w-5xl rounded-md border border-linen bg-french_gray p-4 shadow-md">
			<p class="text-lg text-dark_purple">
				Loading...<br /><br />
				This may take a while depending on the size of your CSV file.
			</p>
		</div>
	{:else}
		{#if data.length > 0}
			<div class="w-full max-w-xs">
				<button
					onclick={downloadData}
					class="my-4 w-full rounded-md border border-linen bg-french_gray p-2 text-dark_purple shadow-md"
				>
					Download Moxfield CSV
				</button>
			</div>
		{/if}

		{#if missingIds.length > 0}
			<div
				class="my-4 max-h-64 w-full max-w-5xl overflow-auto rounded-md border border-linen bg-dark_purple p-4 shadow-md"
			>
				<h2 class="mb-2 text-center text-lg font-bold">Missing CardMarket IDs</h2>
				<div class="grid grid-cols-1 gap-1 sm:grid-cols-9">
					<div class="hidden sm:block"><strong>Line</strong></div>
					<div class="hidden sm:block"><strong>ID</strong></div>
					<div class="hidden sm:col-span-7 sm:block"><strong>Reason</strong></div>
					{#each sortedMissingIds as item, index (item.line)}
						<div class="sm:col-span-1">
							<span class="sm:hidden"><strong>Line: </strong></span>
							{item.line}
						</div>
						<div class="sm:col-span-1">
							<span class="sm:hidden"><strong>ID: </strong></span>
							{item.id}
						</div>
						<div class="sm:col-span-7">
							<span class="sm:hidden"><strong>Reason: </strong></span>
							{#if item.uri}
								This is likely <a href={item.uri} target="_blank" rel="external noopener noreferrer"
									><strong>{item.name}</strong></a
								>. {item.reason}
							{:else if item.expansion}
								{item.reason} This may be <strong>{item.name}</strong> from {item.expansion}.
							{:else}
								{item.reason}
							{/if}
						</div>
						{#if index < sortedMissingIds.length - 1}
							<hr class="sm:hidden" />
						{/if}
					{/each}
				</div>
			</div>

			<button
				onclick={() => {
					const missingIdsText = missingIds.map((item) => item.id).join('\n');
					navigator.clipboard.writeText(missingIdsText);
					copied = true;
					setTimeout(() => (copied = false), 2000);
				}}
				class="my-4 w-full max-w-xs rounded-md border border-linen bg-french_gray p-2 text-dark_purple shadow-md"
				disabled={copied ?? false}
			>
				{copied ? 'Copied!' : 'Copy Missing IDs'}
			</button>
		{/if}
	{/if}

	{#if error}
		<div class="my-4 w-full max-w-xl rounded-md border border-linen bg-slate_blue p-4 shadow-md">
			<h2 class="text-lg font-bold">Error</h2>
			{#if Array.isArray(error)}
				{#each error as errorMessage (errorMessage)}
					<p>{errorMessage}</p>
				{/each}
			{:else}
				<p>{error}</p>
			{/if}
		</div>
	{/if}

	<footer class="mt-8 shrink-0 text-center text-sm lg:fixed lg:right-1 lg:bottom-0 lg:m-1">
		<p>
			Made with <span class="font-sans">&#9749;</span> by
			<a href="https://github.com/Kerakis" target="_blank" rel="noopener noreferrer">
				&nbsp;Kerakis&nbsp;
			</a>
			© {year}
		</p>
	</footer>
</div>

// src/FetchData.jsx
import React, { useState } from 'react';
import axios from 'axios';
import Papa from 'papaparse';
import { saveAs } from 'file-saver';

const year = new Date().getFullYear();

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// Define a function to convert language code to language name
function getLanguageName(code) {
  const languages = {
    1: 'English',
    2: 'French',
    3: 'German',
    4: 'Spanish',
    5: 'Italian',
    6: 'Simplified Chinese',
    7: 'Japanese',
    8: 'Portuguese',
    9: 'Russian',
    10: 'Korean',
    11: 'Traditional Chinese',
  };
  return languages[code] || '';
}

// Define a function to convert condition code to condition name
function getConditionName(code) {
  const conditions = {
    MT: 'M',
    NM: 'NM',
    EX: 'LP',
    GD: 'MP',
    LP: 'MP',
    PL: 'HP',
    PO: 'D',
  };
  return conditions[code] || 'NM';
}

// Define a function to determine the foil status
function getFoil(isFoil, finishes) {
  if (isFoil === '1') {
    if (finishes.includes('etched') && !finishes.includes('foil')) {
      return 'etched';
    } else {
      return 'foil';
    }
  } else {
    return '';
  }
}

function FetchData() {
  const [data, setData] = useState([]);
  const [missingIds, setMissingIds] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [file, setFile] = useState(null);
  const [fileContent, setFileContent] = useState('');
  const [fileChanged, setFileChanged] = useState(true);
  const [copied, setCopied] = useState(null);

  const handleFileUpload = (event) => {
    const file = event.target.files[0];
    setFile(file);
    setFileChanged(true);
    setError(null);

    const reader = new FileReader();
    reader.onload = function (e) {
      setFileContent(e.target.result);
    };
    reader.onerror = function () {
      setError(reader.error.message);
    };
    reader.readAsText(file);
  };

  const handleLoadFile = async () => {
    // Create a queue to store the updates
    const updates = [];

    if (!file) {
      setError('No file selected.');
      setMissingIds([]);
      setData([]);
      setCopied(false);
      setFileChanged(false);
      return;
    }

    setLoading(true);
    setError(null);
    setMissingIds([]);
    setData([]);
    setCopied(false);

    // Parse the CSV file
    Papa.parse(fileContent, {
      header: true,
      complete: async (results) => {
        const fields = results.meta.fields;
        if (
          !(
            fields.includes('idProduct') ||
            (fields.includes('Product ID') &&
              fields.includes('Article') &&
              fields.includes('Expansion'))
          )
        ) {
          setError([
            'Invalid file format.',
            'The file must include either an "idProduct" column header or all three of the following column headers: "Product ID", "Article", and "Expansion".',
            'Are you sure this is a CardMarket CSV file?',
          ]);
          setLoading(false);
          setFileChanged(false);
          setMissingIds([]);
          setData([]);
          setCopied(false);
          return;
        }

        // Fetch data for each Cardmarket ID
        const promises = results.data.map(async (row, index) => {
          await delay(index * 100);

          let isToken = '';
          let expansion = row.Expansion || '';
          let article = row.Article || '';

          expansion = expansion.replace(': Extras', '');
          if (['Mystery Booster', 'The List'].includes(expansion)) {
            expansion = 'PLST';
          } else if (expansion === '30th Anniversary Celebration') {
            expansion = 'P30A';
          }
          if (expansion.includes('Commander:')) {
            expansion = expansion.replace('Commander: ', '');
          }
          expansion = expansion.replace(': Promos', ' Promos');
          article = article.replace(/\(.*\)/, '');
          if (article.includes('Token')) {
            article = article.replace(/Token.*$/, '');
            expansion += ' Tokens';
            isToken = '+t:token';
          }

          const idProduct = row['Product ID'] || row.idProduct;
          const count = row.groupCount || row.Amount;
          const purchasePrice = row.price || row['Article Value'];

          if (row.Category && row.Category !== 'Magic Single') {
            setMissingIds((prevMissingIds) => [
              ...prevMissingIds,
              {
                id: idProduct,
                line: index + 2,
                reason: 'This is not a Magic card.',
              },
            ]);
            return;
          }

          try {
            const response = await axios.get(
              `https://api.scryfall.com/cards/cardmarket/${idProduct}`,
            );
            if (response.status === 200) {
              const card = response.data;

              // When you receive data, add the update to the queue
              updates[index] = (prevData) => [
                ...prevData,
                {
                  Count: count,
                  Name: card.name,
                  Edition: card.set,
                  Language: getLanguageName(row.idLanguage) || '',
                  Foil: getFoil(row.isFoil, card.finishes),
                  CollectorNumber: card.collector_number,
                  Alter: row.isAltered === 'true' ? 'TRUE' : 'FALSE',
                  Condition: getConditionName(row.condition) || 'NM',
                  PurchasePrice: purchasePrice,
                },
              ];
            }
          } catch (err) {
            if (
              err.response &&
              err.response.status === 404 &&
              row.Article &&
              row.Expansion
            ) {
              try {
                const response = await axios.get(
                  `https://api.scryfall.com/cards/search?q=e%3A%22${expansion}%22+${article}${isToken}`,
                );
                if (response.status === 200) {
                  const card = response.data;

                  // When you receive data, add the update to the queue
                  updates[index] = (prevData) => [
                    ...prevData,
                    {
                      Count: count,
                      Name: card.data[0].name,
                      Edition: card.data[0].set,
                      Language: getLanguageName(row.idLanguage) || '',
                      Foil: getFoil(row.isFoil, card.data[0].finishes),
                      CollectorNumber: card.data[0].collector_number,
                      Alter: row.isAltered === 'true' ? 'TRUE' : 'FALSE',
                      Condition: getConditionName(row.condition) || 'NM',
                      PurchasePrice: purchasePrice,
                    },
                  ];
                  setMissingIds((prevMissingIds) => [
                    ...prevMissingIds,
                    {
                      id: idProduct,
                      line: index + 2,
                      name: card.data[0].name,
                      uri: card.data[0].scryfall_uri,
                      reason:
                        'The printing added to your Moxfield CSV may be incorrect.',
                    },
                  ]);
                }
              } catch (err) {
                if (
                  err.response &&
                  err.response.status == 404 &&
                  row.Category == 'Magic Single'
                ) {
                  setMissingIds((prevMissingIds) => [
                    ...prevMissingIds,
                    {
                      id: idProduct,
                      line: index + 2,
                      name: article,
                      expansion: expansion,
                      reason: 'Unable to find this card on Scryfall.',
                    },
                  ]);
                }
              }
            } else if (
              err.response &&
              err.response.status === 404 &&
              !row.Category
            ) {
              setMissingIds((prevMissingIds) => [
                ...prevMissingIds,
                {
                  id: idProduct,
                  line: index + 2,
                  reason: 'Scryfall is missing this CardMarket ID.',
                },
              ]);
            } else {
              if (err.response && err.response.status !== 404) {
                setError(err.message);
              }
              setFileChanged(false);
              setData([]);
              setCopied(false);
            }
          } finally {
            if (index === results.data.length - 1) {
              // Convert the updates object back into an array in the correct order
              const orderedData = Object.keys(updates)
                .sort((a, b) => a - b)
                .map((key) => updates[key]);

              for (let update of orderedData) {
                setData(update);
              }
              setLoading(false);
              setFileChanged(false);
            }
          }
        });
        await Promise.all(promises);
      },
      error: async (err) => {
        setError(err.message);
        setLoading(false);
        setMissingIds([]);
        setData([]);
        setCopied(false);
      },
    });
  };

  const disableLoadButton = loading || !fileChanged;

  // Define a function to download the data as a CSV file
  function downloadData() {
    const csv = Papa.unparse(data);
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    saveAs(blob, 'output.csv');
  }

  const sortedMissingIds = [...missingIds].sort((a, b) =>
    a.reason.localeCompare(b.reason),
  );

  return (
    <div className='flex flex-col items-center justify-center min-h-screen text-linen bg-tropical_indigo px-4'>
      <h1 className='text-5xl lg:mb-24 mb-2 mt-5 text-center font-bold'>
        CardMarket to Moxfield CSV Converter
      </h1>
      <input
        type='file'
        accept='.csv'
        onChange={handleFileUpload}
        className='my-4 p-2 w-full max-w-md bg-french_gray text-dark_purple border border-linen rounded-md shadow-md'
      />
      <button
        onClick={handleLoadFile}
        className={`my-4 p-2 w-full max-w-xs border border-linen rounded-md shadow-md ${
          error ? 'bg-slate_blue text-linen' : 'bg-french_gray text-dark_purple'
        }`}
        disabled={disableLoadButton}>
        {error
          ? 'Error'
          : loading
            ? 'Loading'
            : fileChanged
              ? 'Load CSV File'
              : 'Data Loaded'}
      </button>

      <div
        className={`flex flex-col xl:flex-row space-y-4 xl:space-y-0 xl:space-x-4 my-4 w-full max-w-3xl xl:max-w-6xl ${
          data.length > 0 ? '' : 'xl:flex-col'
        }`}>
        <textarea
          value={
            fileContent ||
            'Please load your CardMarket CSV file. The input data will show here once loaded.'
          }
          readOnly
          className={`p-2 border border-linen bg-dark_purple rounded-md shadow-md resize-none h-50 lg:h-125 ${
            data.length > 0 ? 'xl:w-1/2' : 'xl:w-full'
          }`}
        />
        {data.length > 0 && (
          <textarea
            value={Papa.unparse(data)}
            readOnly
            className='p-2 border border-linen bg-dark_purple rounded-md shadow-md resize-none h-50 lg:h-125 xl:w-1/2'
          />
        )}
      </div>

      {loading ? (
        <div className='my-4 p-4 w-full max-w-5xl bg-french_gray border border-linen rounded-md shadow-md'>
          <p className='text-lg text-dark_purple'>
            Loading...
            <br />
            <br />
            This may take a while depending on the size of your CSV file.
          </p>
        </div>
      ) : (
        <>
          {data.length > 0 && (
            <div className='w-full max-w-xs'>
              <button
                onClick={downloadData}
                className='my-4 p-2 w-full text-dark_purple bg-french_gray border border-linen rounded-md shadow-md'>
                Download Moxfield CSV
              </button>
            </div>
          )}

          {/* Display the missing IDs */}
          {missingIds.length > 0 && (
            <>
              <div className='my-4 p-4 rounded-md shadow-md bg-dark_purple border border-linen overflow-auto w-full max-w-5xl max-h-64'>
                <h2 className='text-lg font-bold mb-2 text-center'>
                  Missing CardMarket IDs
                </h2>
                <div className='grid grid-cols-1 sm:grid-cols-9 gap-1'>
                  <div className='hidden sm:block'>
                    <strong>Line</strong>
                  </div>
                  <div className='hidden sm:block'>
                    <strong>ID</strong>
                  </div>
                  <div className='hidden sm:block sm:col-span-7'>
                    <strong>Reason</strong>
                  </div>
                  {sortedMissingIds.map((item, index) => (
                    <React.Fragment key={item.line}>
                      <div key={index} className='sm:col-span-1'>
                        <span className='sm:hidden'>
                          <strong>Line: </strong>
                        </span>
                        {item.line}
                      </div>
                      <div className='sm:col-span-1'>
                        <span className='sm:hidden'>
                          <strong>ID: </strong>
                        </span>
                        {item.id}
                      </div>
                      <div className='sm:col-span-7'>
                        <span className='sm:hidden'>
                          <strong>Reason: </strong>
                        </span>
                        {item.uri ? (
                          <>
                            This is likely{' '}
                            <a
                              href={item.uri}
                              target='_blank'
                              rel='noopener noreferrer'>
                              <strong>{item.name}</strong>
                            </a>
                            . {item.reason}
                          </>
                        ) : item.expansion ? (
                          <>
                            {item.reason} This may be{' '}
                            <strong>{item.name}</strong> from {item.expansion}.
                          </>
                        ) : (
                          item.reason
                        )}
                      </div>
                      {index < sortedMissingIds.length - 1 && (
                        <hr className='sm:hidden' />
                      )}
                    </React.Fragment>
                  ))}
                </div>
              </div>

              <button
                onClick={() => {
                  const missingIdsText = missingIds
                    .map((item) => item.id)
                    .join('\n');
                  navigator.clipboard.writeText(missingIdsText);
                  setCopied(true);
                  setTimeout(() => setCopied(false), 2000); // Reset the copied state after 2 seconds
                }}
                className='my-4 p-2 text-dark_purple border border-linen bg-french_gray w-full max-w-xs rounded-md shadow-md'
                disabled={copied}>
                {copied ? 'Copied!' : 'Copy Missing IDs'}
              </button>
            </>
          )}
        </>
      )}

      {/* Display the error message */}
      {error && (
        <div className='my-4 p-4 bg-slate_blue border border-linen w-full max-w-xl rounded-md shadow-md'>
          <h2 className='text-lg font-bold'>Error</h2>
          {Array.isArray(error) ? (
            error.map((errorMessage, index) => (
              <p key={index}>{errorMessage}</p>
            ))
          ) : (
            <p>{error}</p>
          )}
        </div>
      )}
      <footer className='shrink-0 mt-8 text-sm text-center lg:fixed lg:m-1 lg:bottom-0 lg:right-1'>
        <p>
          Made with <span className='font-sans'>&#9749;</span> by
          <a
            href='https://github.com/Kerakis'
            target='_blank'
            rel='noopener noreferrer'>
            &nbsp;Kerakis&nbsp;
          </a>
          © {year}
        </p>
      </footer>
    </div>
  );
}

export default FetchData;
